name: pull-request
on:
  pull_request:
    types: [opened, reopened, synchronize]
permissions:
  contents: read
  pull-requests: write

jobs:

  make-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make lint

  make-test-cover:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v4
    - uses: actions/checkout@v3
    - run: make test
    - run: go test ./... -coverprofile=coverprofile
    - run: go install github.com/mattn/goveralls@latest
    - run: goveralls -coverprofile=coverage.out -service=github
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v2
    - run: make docker-build
